"""create initial tables

Revision ID: 0e481e3fd8f0
Revises: 
Create Date: 2026-08-25 07:36:14.564783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e481e3fd8f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=150), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('target_name', sa.String(length=150), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_entries'))
    )
    op.create_index(op.f('ix_audit_entries_action'), 'audit_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_entries_category'), 'audit_entries', ['category'], unique=False)
    op.create_index(op.f('ix_audit_entries_target_id'), 'audit_entries', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_timestamp'), 'audit_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_entries_user_id'), 'audit_entries', ['user_id'], unique=False)
    op.create_table('consumibles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('es_critico', sa.Boolean(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stock >= 0', name=op.f('ck_consumibles_stock_non_negative')),
    sa.CheckConstraint('stock_minimo >= 0', name=op.f('ck_consumibles_minimum_stock_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumibles'))
    )
    op.create_index(op.f('ix_consumibles_es_critico'), 'consumibles', ['es_critico'], unique=False)
    op.create_index(op.f('ix_consumibles_nombre'), 'consumibles', ['nombre'], unique=True)
    op.create_table('empaques',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('servicio', sa.Boolean(), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=False),
    sa.Column('ultima_visita', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empaques'))
    )
    op.create_index(op.f('ix_empaques_nombre'), 'empaques', ['nombre'], unique=True)
    op.create_table('tecnicos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ultima_conexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('cumpleanos', sa.Date(), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tecnicos'))
    )
    op.create_index(op.f('ix_tecnicos_email'), 'tecnicos', ['email'], unique=True)
    op.create_index(op.f('ix_tecnicos_nombre'), 'tecnicos', ['nombre'], unique=False)
    op.create_table('bancos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empaque_id', sa.String(length=36), nullable=False),
    sa.Column('fecha_instalacion', sa.Date(), nullable=False),
    sa.Column('lineas', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empaque_id'], ['empaques.id'], name=op.f('fk_bancos_empaque_id_empaques'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bancos'))
    )
    op.create_index(op.f('ix_bancos_empaque_id'), 'bancos', ['empaque_id'], unique=False)
    op.create_table('cabezales',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('empaque_id', sa.String(length=36), nullable=True),
    sa.Column('freno_actual_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empaque_id'], ['empaques.id'], name=op.f('fk_cabezales_empaque_id_empaques')),
    sa.ForeignKeyConstraint(['freno_actual_id'], ['frenos.id'], name='fk_cabezal_freno_actual', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cabezales'))
    )
    op.create_index(op.f('ix_cabezales_empaque_id'), 'cabezales', ['empaque_id'], unique=False)
    op.create_index(op.f('ix_cabezales_estado'), 'cabezales', ['estado'], unique=False)
    op.create_index(op.f('ix_cabezales_ubicacion'), 'cabezales', ['ubicacion'], unique=False)
    op.create_table('caseteras',
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('empaque_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empaque_id'], ['empaques.id'], name=op.f('fk_caseteras_empaque_id_empaques')),
    sa.PrimaryKeyConstraint('numero', name=op.f('pk_caseteras'))
    )
    op.create_index(op.f('ix_caseteras_empaque_id'), 'caseteras', ['empaque_id'], unique=False)
    op.create_index(op.f('ix_caseteras_estado'), 'caseteras', ['estado'], unique=False)
    op.create_index(op.f('ix_caseteras_ubicacion'), 'caseteras', ['ubicacion'], unique=False)
    op.create_table('frenos',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('cabezal_id', sa.String(length=80), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('empaque_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabezal_id'], ['cabezales.id'], name='fk_freno_cabezal', use_alter=True),
    sa.ForeignKeyConstraint(['empaque_id'], ['empaques.id'], name=op.f('fk_frenos_empaque_id_empaques')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frenos'))
    )
    op.create_index(op.f('ix_frenos_cabezal_id'), 'frenos', ['cabezal_id'], unique=False)
    op.create_index(op.f('ix_frenos_empaque_id'), 'frenos', ['empaque_id'], unique=False)
    op.create_index(op.f('ix_frenos_estado'), 'frenos', ['estado'], unique=False)
    op.create_index(op.f('ix_frenos_ubicacion'), 'frenos', ['ubicacion'], unique=False)
    op.create_table('movimientos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=80), nullable=False),
    sa.Column('machine_type', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tecnico_id', sa.String(length=36), nullable=True),
    sa.Column('tecnico_nombre', sa.String(length=150), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('origen', sa.String(length=255), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], name=op.f('fk_movimientos_tecnico_id_tecnicos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimientos'))
    )
    op.create_index(op.f('ix_movimientos_fecha'), 'movimientos', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_machine_id'), 'movimientos', ['machine_id'], unique=False)
    op.create_index(op.f('ix_movimientos_machine_type'), 'movimientos', ['machine_type'], unique=False)
    op.create_index(op.f('ix_movimientos_tecnico_id'), 'movimientos', ['tecnico_id'], unique=False)
    op.create_table('reemplazos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('retirado_id', sa.String(length=80), nullable=False),
    sa.Column('retirado_tipo', sa.String(length=20), nullable=False),
    sa.Column('instalado_id', sa.String(length=80), nullable=False),
    sa.Column('instalado_tipo', sa.String(length=20), nullable=False),
    sa.Column('empaque_id', sa.String(length=36), nullable=False),
    sa.Column('empaque_nombre', sa.String(length=150), nullable=False),
    sa.Column('tecnico_id', sa.String(length=36), nullable=True),
    sa.Column('tecnico_nombre', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empaque_id'], ['empaques.id'], name=op.f('fk_reemplazos_empaque_id_empaques')),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], name=op.f('fk_reemplazos_tecnico_id_tecnicos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reemplazos'))
    )
    op.create_index(op.f('ix_reemplazos_empaque_id'), 'reemplazos', ['empaque_id'], unique=False)
    op.create_index(op.f('ix_reemplazos_fecha'), 'reemplazos', ['fecha'], unique=False)
    op.create_index(op.f('ix_reemplazos_instalado_id'), 'reemplazos', ['instalado_id'], unique=False)
    op.create_index(op.f('ix_reemplazos_retirado_id'), 'reemplazos', ['retirado_id'], unique=False)
    op.create_index(op.f('ix_reemplazos_tecnico_id'), 'reemplazos', ['tecnico_id'], unique=False)
    op.create_table('servicios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=80), nullable=False),
    sa.Column('machine_type', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resumen', sa.String(length=500), nullable=False),
    sa.Column('trabajo_hecho', sa.Text(), nullable=False),
    sa.Column('tecnico_id', sa.String(length=36), nullable=True),
    sa.Column('tecnico_nombre', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], name=op.f('fk_servicios_tecnico_id_tecnicos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servicios'))
    )
    op.create_index(op.f('ix_servicios_fecha'), 'servicios', ['fecha'], unique=False)
    op.create_index(op.f('ix_servicios_machine_id'), 'servicios', ['machine_id'], unique=False)
    op.create_index(op.f('ix_servicios_machine_type'), 'servicios', ['machine_type'], unique=False)
    op.create_index(op.f('ix_servicios_tecnico_id'), 'servicios', ['tecnico_id'], unique=False)
    op.create_table('visitas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('solicitado_por', sa.String(length=150), nullable=False),
    sa.Column('vehiculo', sa.String(length=30), nullable=False),
    sa.Column('empaque_id', sa.String(length=36), nullable=False),
    sa.Column('estado_sincronizacion', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empaque_id'], ['empaques.id'], name=op.f('fk_visitas_empaque_id_empaques')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitas'))
    )
    op.create_index(op.f('ix_visitas_empaque_id'), 'visitas', ['empaque_id'], unique=False)
    op.create_index(op.f('ix_visitas_estado_sincronizacion'), 'visitas', ['estado_sincronizacion'], unique=False)
    op.create_index(op.f('ix_visitas_fecha'), 'visitas', ['fecha'], unique=False)
    op.create_table('cambios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('lugar', sa.String(length=255), nullable=False),
    sa.Column('retirado_freno_id', sa.String(length=80), nullable=False),
    sa.Column('instalado_freno_id', sa.String(length=80), nullable=False),
    sa.Column('cabezal_id', sa.String(length=80), nullable=False),
    sa.Column('tecnico_id', sa.String(length=36), nullable=True),
    sa.Column('tecnico_nombre', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabezal_id'], ['cabezales.id'], name=op.f('fk_cambios_cabezal_id_cabezales')),
    sa.ForeignKeyConstraint(['instalado_freno_id'], ['frenos.id'], name=op.f('fk_cambios_instalado_freno_id_frenos')),
    sa.ForeignKeyConstraint(['retirado_freno_id'], ['frenos.id'], name=op.f('fk_cambios_retirado_freno_id_frenos')),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], name=op.f('fk_cambios_tecnico_id_tecnicos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cambios'))
    )
    op.create_index(op.f('ix_cambios_cabezal_id'), 'cambios', ['cabezal_id'], unique=False)
    op.create_index(op.f('ix_cambios_fecha'), 'cambios', ['fecha'], unique=False)
    op.create_index(op.f('ix_cambios_instalado_freno_id'), 'cambios', ['instalado_freno_id'], unique=False)
    op.create_index(op.f('ix_cambios_retirado_freno_id'), 'cambios', ['retirado_freno_id'], unique=False)
    op.create_index(op.f('ix_cambios_tecnico_id'), 'cambios', ['tecnico_id'], unique=False)
    op.create_table('reportes_sinclair',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visita_id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('codigo_motivo', sa.String(length=10), nullable=False),
    sa.Column('codigo_origen', sa.String(length=10), nullable=False),
    sa.Column('codigo_tipo_servicio', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuera_de_hora', sa.Boolean(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=False),
    sa.Column('firma_cliente', sa.Text(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=150), nullable=False),
    sa.Column('hora_llamada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('produccion_etiquetada', sa.String(length=255), nullable=True),
    sa.Column('condicion_fruta', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], name=op.f('fk_reportes_sinclair_visita_id_visitas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reportes_sinclair'))
    )
    op.create_index(op.f('ix_reportes_sinclair_numero'), 'reportes_sinclair', ['numero'], unique=True)
    op.create_index(op.f('ix_reportes_sinclair_visita_id'), 'reportes_sinclair', ['visita_id'], unique=True)
    op.create_table('servicio_consumibles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servicio_id', sa.String(length=36), nullable=False),
    sa.Column('consumible_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consumible_id'], ['consumibles.id'], name=op.f('fk_servicio_consumibles_consumible_id_consumibles')),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], name=op.f('fk_servicio_consumibles_servicio_id_servicios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servicio_consumibles')),
    sa.UniqueConstraint('servicio_id', 'consumible_id', name=op.f('uq_servicio_consumibles_servicio_id'))
    )
    op.create_index(op.f('ix_servicio_consumibles_consumible_id'), 'servicio_consumibles', ['consumible_id'], unique=False)
    op.create_index(op.f('ix_servicio_consumibles_servicio_id'), 'servicio_consumibles', ['servicio_id'], unique=False)
    op.create_table('visita_tecnicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visita_id', sa.String(length=36), nullable=False),
    sa.Column('tecnico_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], name=op.f('fk_visita_tecnicos_tecnico_id_tecnicos')),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], name=op.f('fk_visita_tecnicos_visita_id_visitas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visita_tecnicos')),
    sa.UniqueConstraint('visita_id', 'tecnico_id', name=op.f('uq_visita_tecnicos_visita_id'))
    )
    op.create_index(op.f('ix_visita_tecnicos_tecnico_id'), 'visita_tecnicos', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_visita_tecnicos_visita_id'), 'visita_tecnicos', ['visita_id'], unique=False)
    op.create_table('reporte_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporte_id', sa.String(length=36), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('codigo_res', sa.String(length=50), nullable=False),
    sa.Column('numero_partes', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.String(length=100), nullable=False),
    sa.Column('otras_acciones', sa.Text(), nullable=False),
    sa.Column('pct_etiquetado_esperado', sa.Float(), nullable=False),
    sa.Column('pct_etiquetado_real', sa.Float(), nullable=False),
    sa.Column('tiempo_servicio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes_sinclair.id'], name=op.f('fk_reporte_items_reporte_id_reportes_sinclair'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reporte_items')),
    sa.UniqueConstraint('reporte_id', 'orden', name=op.f('uq_reporte_items_reporte_id'))
    )
    op.create_index(op.f('ix_reporte_items_reporte_id'), 'reporte_items', ['reporte_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reporte_items_reporte_id'), table_name='reporte_items')
    op.drop_table('reporte_items')
    op.drop_index(op.f('ix_visita_tecnicos_visita_id'), table_name='visita_tecnicos')
    op.drop_index(op.f('ix_visita_tecnicos_tecnico_id'), table_name='visita_tecnicos')
    op.drop_table('visita_tecnicos')
    op.drop_index(op.f('ix_servicio_consumibles_servicio_id'), table_name='servicio_consumibles')
    op.drop_index(op.f('ix_servicio_consumibles_consumible_id'), table_name='servicio_consumibles')
    op.drop_table('servicio_consumibles')
    op.drop_index(op.f('ix_reportes_sinclair_visita_id'), table_name='reportes_sinclair')
    op.drop_index(op.f('ix_reportes_sinclair_numero'), table_name='reportes_sinclair')
    op.drop_table('reportes_sinclair')
    op.drop_index(op.f('ix_cambios_tecnico_id'), table_name='cambios')
    op.drop_index(op.f('ix_cambios_retirado_freno_id'), table_name='cambios')
    op.drop_index(op.f('ix_cambios_instalado_freno_id'), table_name='cambios')
    op.drop_index(op.f('ix_cambios_fecha'), table_name='cambios')
    op.drop_index(op.f('ix_cambios_cabezal_id'), table_name='cambios')
    op.drop_table('cambios')
    op.drop_index(op.f('ix_visitas_fecha'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_estado_sincronizacion'), table_name='visitas')
    op.drop_index(op.f('ix_visitas_empaque_id'), table_name='visitas')
    op.drop_table('visitas')
    op.drop_index(op.f('ix_servicios_tecnico_id'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_machine_type'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_machine_id'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_fecha'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_reemplazos_tecnico_id'), table_name='reemplazos')
    op.drop_index(op.f('ix_reemplazos_retirado_id'), table_name='reemplazos')
    op.drop_index(op.f('ix_reemplazos_instalado_id'), table_name='reemplazos')
    op.drop_index(op.f('ix_reemplazos_fecha'), table_name='reemplazos')
    op.drop_index(op.f('ix_reemplazos_empaque_id'), table_name='reemplazos')
    op.drop_table('reemplazos')
    op.drop_index(op.f('ix_movimientos_tecnico_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_machine_type'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_machine_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_fecha'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_frenos_ubicacion'), table_name='frenos')
    op.drop_index(op.f('ix_frenos_estado'), table_name='frenos')
    op.drop_index(op.f('ix_frenos_empaque_id'), table_name='frenos')
    op.drop_index(op.f('ix_frenos_cabezal_id'), table_name='frenos')
    op.drop_table('frenos')
    op.drop_index(op.f('ix_caseteras_ubicacion'), table_name='caseteras')
    op.drop_index(op.f('ix_caseteras_estado'), table_name='caseteras')
    op.drop_index(op.f('ix_caseteras_empaque_id'), table_name='caseteras')
    op.drop_table('caseteras')
    op.drop_index(op.f('ix_cabezales_ubicacion'), table_name='cabezales')
    op.drop_index(op.f('ix_cabezales_estado'), table_name='cabezales')
    op.drop_index(op.f('ix_cabezales_empaque_id'), table_name='cabezales')
    op.drop_table('cabezales')
    op.drop_index(op.f('ix_bancos_empaque_id'), table_name='bancos')
    op.drop_table('bancos')
    op.drop_index(op.f('ix_tecnicos_nombre'), table_name='tecnicos')
    op.drop_index(op.f('ix_tecnicos_email'), table_name='tecnicos')
    op.drop_table('tecnicos')
    op.drop_index(op.f('ix_empaques_nombre'), table_name='empaques')
    op.drop_table('empaques')
    op.drop_index(op.f('ix_consumibles_nombre'), table_name='consumibles')
    op.drop_index(op.f('ix_consumibles_es_critico'), table_name='consumibles')
    op.drop_table('consumibles')
    op.drop_index(op.f('ix_audit_entries_user_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_timestamp'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_target_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_category'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_action'), table_name='audit_entries')
    op.drop_table('audit_entries')
    # ### end Alembic commands ###
