"""perimtir cambio de freno de un cabezal sin freno

Revision ID: 2c4347ec2715
Revises: 0e481e3fd8f0
Create Date: 2026-08-30 12:52:58.007967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4347ec2715'
down_revision: Union[str, Sequence[str], None] = '0e481e3fd8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_cabezal_freno_actual', 'cabezales', 'frenos', ['freno_actual_id'], ['id'], use_alter=True)
    op.alter_column('cambios', 'retirado_freno_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.create_foreign_key('fk_freno_cabezal', 'frenos', 'cabezales', ['cabezal_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_freno_cabezal', 'frenos', type_='foreignkey')
    op.alter_column('cambios', 'retirado_freno_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_constraint('fk_cabezal_freno_actual', 'cabezales', type_='foreignkey')
    # ### end Alembic commands ###
