"""modifico la estructura de reportes

Revision ID: 4bad8bf1e5ec
Revises: f5da0b3c3a4d
Create Date: 2026-09-30 08:39:48.393662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bad8bf1e5ec'
down_revision: Union[str, Sequence[str], None] = 'f5da0b3c3a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reporte_items', sa.Column('numero_de_serie', sa.String(length=50), nullable=False))
    op.add_column('reporte_items', sa.Column('codigo_motivo', sa.String(length=50), nullable=False))
    op.add_column('reporte_items', sa.Column('codigo_origen', sa.String(length=50), nullable=False))
    op.alter_column('reportes_sinclair', 'codigo_motivo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('reportes_sinclair', 'codigo_origen',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('reportes_sinclair', 'codigo_tipo_servicio',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reportes_sinclair', 'codigo_tipo_servicio',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('reportes_sinclair', 'codigo_origen',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('reportes_sinclair', 'codigo_motivo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('reporte_items', 'codigo_origen')
    op.drop_column('reporte_items', 'codigo_motivo')
    op.drop_column('reporte_items', 'numero_de_serie')
    # ### end Alembic commands ###
