"""permito el reemplazo sin equipo retirado

Revision ID: 513fb6b5d360
Revises: 4bad8bf1e5ec
Create Date: 2026-10-02 12:13:37.506261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513fb6b5d360'
down_revision: Union[str, Sequence[str], None] = '4bad8bf1e5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reemplazos",
        "retirado_id",
        existing_type=sa.VARCHAR(length=80),
        nullable=True,
    )
    op.alter_column(
        "reemplazos",
        "retirado_tipo",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reportes_sinclair', 'codigo_tipo_servicio',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('reportes_sinclair', 'codigo_origen',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('reportes_sinclair', 'codigo_motivo',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('reportes_sinclair', 'numero',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.add_column('reporte_items', sa.Column('codigo_origen', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('reporte_items', sa.Column('codigo_motivo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('reporte_items', sa.Column('numero_de_serie', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('reemplazos', 'retirado_tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('reemplazos', 'retirado_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
