"""cambiar numero de reporte a string

Revision ID: f5da0b3c3a4d
Revises: 2c4347ec2715
Create Date: 2026-09-29 11:50:48.798982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5da0b3c3a4d'
down_revision: Union[str, Sequence[str], None] = '2c4347ec2715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reportes_sinclair', 'numero',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reportes_sinclair', 'numero',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
